# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# Where the magic happens.
export DOTFILES=~/.dotfiles

#local
PATH=$HOME/local/bin:$PATH
#.local
PATH=$HOME/.local/bin:$PATH
MANPATH=$HOME/.local/man:$MANPATH
LD_LIBRARY_PATH=$HOME/.local/lib64:$HOME/.local/lib:$LD_LIBRARY_PATH
#home
PATH=$HOME/bin:$PATH
PATH=$DOTFILES/bin:$PATH

export PATH
export MANPATH
export LD_LIBRARY_PATH


# Source all files in "lib"
source_lib_files() {
  local file
  if [[ "$1" ]]; then
    source "$DOTFILES/lib/$1.sh"
  else
    for file in $DOTFILES/lib/*; do
      source "$file"
    done
  fi
}

# Run dotfiles script, then source.
dotfiles() {
  $DOTFILES/bin/dotfiles "$@" && source_lib_files
}

source_lib_files


