#! /usr/bin/env bash
# papis-short-help:  Email a paper to my friend

if [[ $1 = "-h" ]]; then
  echo "Email a paper to my friend"
  exit 0
fi

folder_name=$1
zip_name="${folder_name}.zip"

papis -l ${PAPIS_LIB} export --folder --out ${folder_name}
zip -r ${zip_name} ${folder_name}

mutt -a ${zip_name}


