#! /usr/bin/env python3

import sys

if len(sys.argv) > 1 and sys.argv[1] == "-h":
    print("Print contact information in mutt format")
    sys.exit(0)

import os
import papis.utils

search_string = sys.argv[1] if len(sys.argv) > 1 else ""

docs = papis.utils.get_documents_in_lib(papis.utils.get_lib(), search_string)

print("Name  <email>")
for contact in docs:
    for t in contact["email"].keys():
        email = contact["email"][t]
        if not email:
            continue
        string = "{doc[first_name]} {doc[last_name]}  <{email}>".format(
            doc=contact, email=email
        )
        print(string)



#vim-run: papis -l contacts mutt ale
