#! /usr/bin/env python3

import sys
import os
import papis.utils

if len(sys.argv) > 1 and sys.argv[1] == "-h":
    print("Print contact information in mutt format")
    sys.exit(0)

search_string = sys.argv[1] if len(sys.argv) > 1 else ""

docs = papis.utils.get_documents_in_lib(os.environ["PAPIS_LIB"], search_string)

print("Name  <email>")
for contact in docs:
    for t in contact["email"].keys():
        email = contact["email"][t]
        if not email:
            continue
        string = "{c[first_name]} {c[last_name]}  <{email}>".format(c=contact, email=email)
        print(string)



#vim-run: papis -l contacts mutt ale
