#! /usr/bin/env python3
# papis-short-help: Print contact information in mutt format

import sys
import logging

logging.basicConfig(level=logging.DEBUG)

if len(sys.argv) > 1 and sys.argv[1] == "-h":
    print("Print contact information in mutt format")
    sys.exit(0)

import os
import papis.utils
import papis.config

search_string = sys.argv[1] if len(sys.argv) > 1 else ""

docs = papis.utils.get_documents_in_lib(papis.config.get_lib(), search=search_string)

papis.config.set('picktool', 'rofi')

contact = papis.utils.pick(
    docs
)

phone = papis.utils.pick(
    list(contact['tel']),
    dict(
        header_filter=lambda x: 
        x + '\n' + str(contact['tel'][x]) if contact['tel'][x] else '-'
    )
)

number = contact['tel'][phone]

os.system('skypeforlinux %s' % number)





#vim-run: papis -v -l contacts call ale
