#! /usr/bin/env bash
# papis-short-help:  Rough dmenu-based gui
# Copyright © 2018 Alejandro Gallo. GPLv3

if [[ $1 = "-h" ]]; then
  echo "Rough dmenu-based gui"
  cat <<EOF
Usage: papis dmenu
EOF
  exit 0
fi

query=$(
echo -n |
dmenu \
-b \
-i \
-l "10" \
-fn "monospace-14" \
-nb "#000000" \
-nf "#55ff55" \
-sb "#005500" \
-sf "#f0f0f0" \
-p 'Query:'
)

if [[ -n "${query}" ]]; then

  papis \
    --pick-lib \
    --set header-format \
        "{doc[title]:<70.70}|{doc[author]:<20.20} ({doc[year]:-<4})" \
    --set picktool dmenu \
    open "$query"

fi
