#! /usr/bin/env python3
# papis-short-help: Print contact information in mutt format

import sys

if len(sys.argv) > 1 and sys.argv[1] == "-h":
    print("Print contact information in mutt format")
    sys.exit(0)

import os
import papis.api

search_string = sys.argv[1] if len(sys.argv) > 1 else ""

docs = papis.api.get_documents_in_lib(
    search=search_string, library=papis.api.get_lib()
)

print("Name  <email>")
for contact in docs:
    for t in contact["email"].keys():
        email = contact["email"][t]
        if not email:
            continue
        string = "{doc[first_name]} {doc[last_name]}  <{email}>".format(
            doc=contact, email=email
        )
        print(string)



#vim-run: papis -l contacts mutt ale
